global:
  scrape_interval: 5s
  scrape_timeout: 5s

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'localhost:8000'
          - 'localhost:9091'
#todo(migryz) these should be configured differently for mac/linux