global:
  scrape_interval: 5s
  scrape_timeout: 5s

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          # Default temporal-server
          - 'localhost:8000'
          - 'host.docker.internal:8000'
          # Default hellow-world example
          # - 'localhost:9091'
          # - 'host.docker.internal:9091'
