# Include this file to run Prometheus as one more dependency:
# docker-compose -f docker-compose.yml -f docker-compose.linux.yml -f docker-compose.prometheus.yml up
version: "3.5"

services:
  prometheus:
    image: prom/prometheus
    container_name: temporal-prometheus
    volumes:
      - ./prometheus_dev:/etc/prometheus
    network_mode: host
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
#    dashboards:
#      default:
#        frontend-github:
#          url: https://raw.githubusercontent.com/temporalio/temporal-dashboards/master/dashboards/frontend.json
#          datasource: TemporalMetrics
#        temporal-github:
#          url: https://raw.githubusercontent.com/temporalio/temporal-dashboards/master/dashboards/temporal.json
#          datasource: TemporalMetrics
#        history-github:
#          url: https://raw.githubusercontent.com/temporalio/temporal-dashboards/master/dashboards/history.json
#          datasource: TemporalMetrics
#        matching-github:
#          url: https://raw.githubusercontent.com/temporalio/temporal-dashboards/master/dashboards/matching.json
#          datasource: TemporalMetrics
#        clusteroverview-github:
#          url: https://raw.githubusercontent.com/temporalio/temporal-dashboards/master/dashboards/10000.json
#          datasource: TemporalMetrics
#        common-github:
#          url: https://raw.githubusercontent.com/temporalio/temporal-dashboards/master/dashboards/common.json
#          datasource: TemporalMetrics
#    datasources:
#      datasources.yaml:
#        apiVersion: 1
#        datasources:
#          - name: TemporalMetrics
#            type: prometheus
#            url: http://prometheus:9090
#            isDefault: true
